// All Icons used for the global layout 
export {default as SearchIcon} from "./SearchIcon.svg"
export {default as AlarmIcon} from "./AlarmIcon.svg"
export {default as PortfolioIcon} from "./PortfolioIcon.svg"
export {default as BackArrowIcon} from "./BackArrowIcon.svg"
export {default as LogoIcon} from "./LogoIcon.svg"
export {default as FoldSideBarIcon} from "./FoldSidebarIcon.svg"
export {default as TransactionIcon} from "./TransactionIcon.svg"
export {default as AssetDistributionIcon} from "./AssetDistributionIcon.svg"
export {default as DefiIcon} from "./DefiIcon.svg"
export {default as DerivativesIcon} from "./DerivativesIcon.svg"
export {default as ExplorerIcon} from "./ExplorerIcon.svg"
export {default as HelpIcon} from "./HelpIcon.svg"
export {default as NftsIcon} from "./NftsIcon.svg"
export {default as ReportsIcon} from "./ReportsIcon.svg"
export {default as SettingsIcon} from "./SettingsIcon.svg"
export {default as SnapshotIcon} from "./SnapshotIcon.svg"
export {default as WatchListIcon} from "./WatchListIcon.svg"
